### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Asphyixii** [thelevicole/youtube-to-html5-loader#8]
The video appears however there isnt any audio

**Comment by thelevicole** [comment]
Some streams from YouTube have no audio channel so this might be where the issue lies. Because of this there has been added a new option to the library (v4) which will only select streams with audio avialable. This can be use like so:

```javascript
new YouTubeToHtml5({
    withAudio: true
});
```

A working example of this can be found here: https://thelevicole.com/youtube-to-html5-loader/
